# Generated by Django 3.2.3 on 2022-12-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavesrequest',
            old_name='Duration_From',
            new_name='duration_from',
        ),
        migrations.RenameField(
            model_name='leavesrequest',
            old_name='Duration_To',
            new_name='duration_to',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
